### ISSUE TITLE
NDR - How you created the demo site?

### ISSUE THREAD

**Issue by munirkamal** [garciaalvaro/post-meta-controls#1]
Hi,

Sorry, this is not an issue or directly related question about this plugin. I just wonder if you can explain or provide the code/library you used to create the demo site with the Gutenberg instance on the page limited to your block?
https://gutenberg-showcase.melonpan.io/post-meta-controls

TIA

**Comment by garciaalvaro** [comment]
Hi!

No problem. It's created in JavaScript, using the [packages](https://github.com/WordPress/gutenberg/tree/master/packages) from the Gutenberg editor. Once I have the time, I plan to release a JS plugin so others might find it useful.

A similar example can be found inside the Gutenberg project, [here](https://github.com/WordPress/gutenberg/tree/master/storybook/stories/playground). Let me know if you have any other doubt.

**Comment by garciaalvaro** [comment]
I'm closing this issue now. Will update if I have more info in the future. Thanks.
