### ISSUE TITLE
Displaying Custom Fields in Block Editor settings prevents PMC updates

### ISSUE THREAD

**Issue by thetwopct** [garciaalvaro/post-meta-controls#6]
Putting this here for information as we wasted an hour on it! 😂

One of our users was experiencing an issue where any updates to the sidebar (PMC) would not save. 

Other users could save just fine. 

We assumed a server / plugin / code issue. But it was much simpler. 

The user had activated the display of the "Custom fields" panel on the page via Block Editor settings. 

When "Custom fields" panel displays, any values updated in the sidebar (PMC) will be ignored when the page is saved. 

So please make sure "custom field" panel is off when using PMC 👍
![2021-01-18-145937@2x](https://user-images.githubusercontent.com/10615884/104931109-e3b59d80-599d-11eb-8fe0-02a40cae15c9.jpg)

**Comment by garciaalvaro** [comment]
Hi, thank you for sharing this conflict.

It seems like it is an open issue in Gutenberg with meta manipulation and Custom fields activated, as you describe.
See: https://github.com/WordPress/gutenberg/issues/23078
I am going to comment about it there too.

I will close this issue for now and hope it can help others in the future.
Thank you!
